// ============================================================================
// PM2 — Fleet services supervisor (24/7)
// ============================================================================
// Revived services that must stay up around the clock, each on its canonical
// port from ports.ts. Matches the pattern of ecosystem.marketing.config.js.
// ============================================================================

const fs = require("node:fs");
const path = require("node:path");

const ORCH_DIR = __dirname;
const ENV_LOCAL = path.join(ORCH_DIR, ".env.local");

function loadEnvLocal() {
  const env = {};
  try {
    const raw = fs.readFileSync(ENV_LOCAL, "utf8");
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
      if (m && !(m[1] in env)) env[m[1]] = m[2].replace(/^"|"$/g, "");
    }
  } catch {}
  return env;
}

const D = loadEnvLocal();
const PYTHON = process.env.PYTHON_PATH || "C:\\Program Files\\Python312\\python.exe";
const NODE = "C:\\Program Files\\nodejs\\node.exe";
const TSX = (rel) => path.join(ORCH_DIR, rel);

module.exports = {
  apps: [
    {
      name: "cloudflared",
      script: "C:\\Program Files (x86)\\cloudflared\\cloudflared.exe",
      args: "tunnel --config C:\\Users\\User\\.cloudflared\\config.yml run",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "256M",
      restart_delay: 5000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 200,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "cloudflared-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "cloudflared-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
    },
    {
      name: "hermes-brain",
      script: "server.js",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\Draymond-Orchestrator\\hermes-proxy",
      interpreter: NODE,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "1G",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "hermes-brain-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "hermes-brain-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: {
        HERMES_PROXY_PORT: "8642",
        NODE_ENV: "production",
        API_SERVER_HOST: D.API_SERVER_HOST || "127.0.0.1",
        API_SERVER_PORT: D.API_SERVER_PORT || "8642",
        API_SERVER_KEY: D.API_SERVER_KEY || "",
      },
    },
    {
      name: "squad-service",
      script: "squad-service.js",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\Draymond-Orchestrator\\hermes-proxy",
      interpreter: NODE,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "squad-service-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "squad-service-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: {
        SQUAD_PORT: "8650",
        NODE_ENV: "production",
      },
    },
    {
      name: "aetherdesk",
      script: PYTHON,
      args: "-m uvicorn src.api.main:app --host 127.0.0.1 --port 8002",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\04_Integrations\\Aetherdesk-Call-Center",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "1G",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "aetherdesk-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "aetherdesk-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: { ...D, NODE_ENV: "production" },
    },
    {
      name: "bookbridge",
      script: PYTHON,
      args: "main.py --http-only",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\Draymond-Orchestrator\\agents\\BookBridge--main",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "1G",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "bookbridge-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "bookbridge-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: { ...D, NODE_ENV: "production" },
    },
    {
      name: "uplift-agent",
      script: "server.js",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\Draymond-Orchestrator\\agents\\Uplift-Agent",
      interpreter: NODE,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "1G",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "uplift-agent-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "uplift-agent-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: {
        UPLIFT_PORT: "8000",
        NODE_ENV: "production",
        ...D,
      },
    },
    {
      name: "sub-team",
      script: PYTHON,
      args: "main.py --serve --port 8050 --host 0.0.0.0",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\Draymond-Orchestrator\\agents\\Sub-Team-main",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "1G",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "sub-team-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "sub-team-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: { ...D, NODE_ENV: "production" },
    },
    {
      name: "overlay-chain",
      script: PYTHON,
      args: "-m uvicorn main:app --host 127.0.0.1 --port 3020",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\Draymond-Orchestrator\\agents\\OverlayChain-Service",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "overlay-chain-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "overlay-chain-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: { ...D, NODE_ENV: "production" },
    },
    {
      name: "indy-music",
      script: PYTHON,
      args: "-m uvicorn main:app --host 127.0.0.1 --port 8020",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\Draymond-Orchestrator\\agents\\IndyMusic-Service",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "indy-music-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "indy-music-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: { ...D, NODE_ENV: "production" },
    },
    {
      name: "litellm",
      script: "C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\litellm.exe",
      args: "--config litellm.yaml --port 4100",
      cwd: ORCH_DIR,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "1G",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "litellm-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "litellm-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: {
        ...D,
        NODE_ENV: "production",
        LITELLM_PORT: "4100",
        // Environment fallbacks litellm.yaml references
        OPENROUTER_API_KEY: D.OPENROUTER_API_KEY || "",
      },
    },
    {
      name: "hemp-os",
      script: "server.ts",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\potential\\Hemp-OS-main",
      interpreter: NODE,
      node_args: "--import tsx",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "1G",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "hemp-os-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "hemp-os-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: {
        PORT: "3100",
        NODE_ENV: "production",
        ...D,
      },
    },
    {
      name: "bet-buddy",
      script: "dist/server.js",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\Draymond-Orchestrator\\agents\\Sports-Steve-main\\Bet-Buddy--main\\backend",
      interpreter: NODE,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "bet-buddy-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "bet-buddy-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: { PORT: "3001", NODE_ENV: "production", ...D },
    },
    {
      name: "bbtech-web-app",
      script: "server.ts",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\02_Pillars\\Overlay Science\\Shared\\bb_tech_core\\bbtech-web-app",
      interpreter: NODE,
      node_args: "--import tsx",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "1G",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "bbtech-web-app-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "bbtech-web-app-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: {
        PORT: "3061",
        NODE_ENV: "production",
        ...D,
      },
    },
    {
      name: "system-agent",
      script: TSX("agents/system-agent/node_modules/tsx/dist/cli.mjs"),
      args: "src/server.ts",
      cwd: path.join(ORCH_DIR, "agents", "system-agent"),
      interpreter: NODE,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "system-agent-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "system-agent-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: {
        SYSTEM_AGENT_PORT: "3405",
        NODE_ENV: "development",
        SYSTEM_AGENT_KEY: D.SYSTEM_AGENT_KEY || "",
        SYSTEM_AGENT_APPROVAL_SECRET: D.SYSTEM_AGENT_APPROVAL_SECRET || "",
      },
    },
    {
      name: "openchat",
      script: path.join("C:\\Users\\User\\Downloads\\Uplift", "Open-Chat", "node_modules", "vite", "bin", "vite.js"),
      args: "--port 5175 --strictPort",
      cwd: "C:\\Users\\User\\Downloads\\Uplift\\Open-Chat",
      interpreter: NODE,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "512M",
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: "10s",
      exp_backoff_restart_delay: 100,
      time: true,
      merge_logs: true,
      out_file: path.join(ORCH_DIR, "data", "logs", "openchat-out.log"),
      error_file: path.join(ORCH_DIR, "data", "logs", "openchat-error.log"),
      log_date_format: "YYYY-MM-DD HH:mm:ss.SSS",
      env: {
        NODE_ENV: "development",
        PORT: "5175",
      },
    },
  ],
};
