// ============================================================================
// DRAYMOND ORCHESTRATION SYSTEM — Registry Seed Data
// ============================================================================
// All 50+ agents, tools, skills, extensions, and services in the
// Uplift Lab ecosystem, ready to be registered in the unified registry.
// ============================================================================

import type { DraymondEntityInsert } from './types';

// ============================================================================
// AGENTS
// ============================================================================

const agents: DraymondEntityInsert[] = [
  {
    name: 'Uplift Agent',
    slug: 'uplift-agent',
    kind: 'agent',
    description: 'Full CLI agent (Hermes fork) with 52+ tools (including Sub Team CPU pipeline and MegaCode bridge), 193+ skills (superpowers, Claude/CCE, domain-specific), 78 extensions, and plugin architecture. The primary Uplift Lab agent.',
    version: '1.0.0',
    tags: ['core', 'cli', 'hermes', 'extensible', 'sub-team', 'megacode', 'skills'],
    category: 'core',
    sector: 'community',
    invocation_method: 'cli_command',
    invocation_config: { command: 'python', args: ['-m', 'agent'], cwd: 'downloads/Uplift Agent' },
    capabilities: ['chat', 'search', 'analysis', 'generation', 'automation', 'orchestration', 'cpu_rtl_generation', 'code_completion', 'skill_execution', 'sub_team_pipeline', 'megacode_bridge'],
    source_type: 'github',
    source_url: 'https://github.com/theupliftlab/uplift-agent',
    download_path: 'downloads/Uplift Agent',
    is_integrated: true,
    platform_page: '/tools/uplift-agent',
    is_free: false,
    price_cents: 2000,
  },
  {
    name: 'Draymond',
    slug: 'draymond',
    kind: 'agent',
    description: 'Intelligent Agent Supervision Layer — the OS for the agent ecosystem. Confidence gating, tiered memory, audit trail, handoff protocol.',
    version: '1.0.0',
    tags: ['core', 'orchestration', 'supervision', 'infrastructure'],
    category: 'infrastructure',
    sector: 'community',
    invocation_method: 'internal',
    invocation_config: { module_path: '@/lib/draymond' },
    capabilities: ['orchestration', 'monitoring', 'memory', 'audit', 'confidence-gating'],
    is_integrated: true,
    platform_page: '/admin/draymond',
  },
  {
    name: 'OTM Agent',
    slug: 'otm-agent',
    kind: 'agent',
    description: 'Out The Mud bootstrapping agent — scans Upwork, Fiverr, Reddit, and Clickworker for opportunities, scores them, and tracks bankroll and time allocation.',
    version: '1.0.0',
    tags: ['income', 'freelance', 'automation', 'opportunities'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'http_api',
    invocation_config: {
      // OpenClaw plugin; OTM Agent API server runs at localhost:3000
      // URL set at runtime via env — do not hardcode
      method: 'POST',
      plugin_entry: 'downloads/Uplift Agent/extensions/otm-agent/index.ts',
    },
    capabilities: ['automation', 'generation', 'outreach', 'opportunity-scanning'],
    download_path: 'downloads/Uplift Agent/extensions/otm-agent',
    is_free: false,
    price_cents: 2000,
  },
  {
    name: 'Sports Steve',
    slug: 'sports-steve',
    kind: 'agent',
    description: 'FastAPI betting intelligence agent — real-time odds, statistical modeling, and bankroll management.',
    version: '1.0.0',
    tags: ['sports', 'betting', 'analytics', 'fastapi'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'api_call',
    invocation_config: { method: 'POST' }, // URL set at runtime via env; no hardcoded localhost
    capabilities: ['analysis', 'search', 'prediction', 'betting'],
    source_type: 'github',
    download_path: 'downloads/Sports-Steve-main',
    is_integrated: true,
    platform_page: '/tools/sports-bundle',
    is_free: false,
    price_cents: 2000,
  },
  {
    name: 'Bet Buddy',
    slug: 'bet-buddy',
    kind: 'service',
    description: 'Betting companion agent — works alongside Sports Steve for conversational betting advice and tracking.',
    version: '1.0.0',
    tags: ['sports', 'betting', 'companion'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'cli_command',
    invocation_config: { command: 'python', args: ['main.py'], cwd: 'downloads/Bet-Buddy--main' },
    capabilities: ['chat', 'analysis', 'betting'],
    source_type: 'github',
    download_path: 'downloads/Bet-Buddy--main',
    is_integrated: true,
    platform_page: '/tools/sports-bundle',
    is_free: false,
    price_cents: 2000,
  },
  {
    name: 'Lil Homie',
    slug: 'lil-homie',
    kind: 'agent',
    description: 'Nanobot assistant — lightweight task runner for quick automations.',
    version: '1.0.0',
    tags: ['nanobot', 'lightweight', 'automation'],
    category: 'dev-tools',
    sector: 'community',
    invocation_method: 'cli_command',
    capabilities: ['chat', 'automation'],
    download_path: 'downloads/Uplift Agent',
  },
  {
    name: 'Hemp-OS',
    slug: 'hemp-os',
    kind: 'agent',
    description: 'Deterministic scientific operating system for hemp processing, biomanufacturing simulation, and computational research. The autonomous Intelligence Orchestrator cross-references all datasets on a 6-hour cycle, detects new insights, spawns research tasks from data gaps, and auto-produces public education content from new discoveries.',
    version: '1.0.0',
    tags: ['hemp', 'research', 'simulation', 'kernel', 'autonomy', 'biomanufacturing'],
    category: 'research',
    sector: 'ventures',
    invocation_method: 'http_api',
    invocation_config: {
      url: 'http://localhost:3100', // HEMP_OS_URL at runtime — do not hardcode
      method: 'POST',
      health_url: 'http://localhost:3100/health',
      endpoints: {
        kernel: '/api/kernel',
        ai: '/api/ai',
        ingest: '/api/ingest',
        ollama: '/api/ollama',
        integration: '/api/integration',
      },
      requires_env: ['HEMP_OS_URL', 'GEMINI_API_KEY'],
    },
    capabilities: [
      'research',
      'simulation',
      'analysis',
      'generation',
      'automation',
      'orchestration',
      'cross_referencing',
      'content_generation',
      'paper_generation',
    ],
    download_path: 'potential/Hemp-OS-main',
    is_integrated: true,
    risk_level_default: 'low',
  },
];

// ============================================================================
// TOOLS / SOFTWARE
// ============================================================================

const tools: DraymondEntityInsert[] = [
  {
    name: 'MegaCode',
    slug: 'megacode',
    kind: 'tool',
    description: 'AI coding assistant — multi-model code generation, refactoring, and debugging.',
    version: '1.0.0',
    tags: ['coding', 'ai', 'multi-model'],
    category: 'dev-tools',
    sector: 'learn',
    invocation_method: 'cli_command',
    capabilities: ['generation', 'analysis', 'code-review', 'refactoring'],
    is_free: false,
    price_cents: 2000,
  },
  {
    name: 'Mutly',
    slug: 'mutly',
    kind: 'tool',
    description: 'Developer daemon & IDE companion — codebase indexing, TypeScript AST symbol extraction, semantic vector search (gemini embeddings + cosine), sandboxed test execution, and a gateway that proxies RepoRank progress / VibeServe tools / Claw-Protect audits. Runs on localhost:4000.',
    version: '1.0.0',
    tags: ['ide', 'daemon', 'indexing', 'semantic-search', 'sandbox', 'gateway'],
    category: 'engineering',
    sector: 'community',
    invocation_method: 'http_api',
    invocation_config: {
      // URL set at runtime via env — do not hardcode localhost
      url: 'http://localhost:4000', // MUTLY_URL
      method: 'POST',
      timeout_ms: 120000,
      endpoints: {
        analyze: { path: '/api/agent/analyze', method: 'POST' },
        scan: { path: '/api/agent/scan', method: 'POST' },
        symbols: { path: '/api/agent/symbols', method: 'GET' },
        pipeline_start: { path: '/api/pipeline/start', method: 'POST' },
        pipeline_status: { path: '/api/pipeline/status/:pipelineId', method: 'GET' },
        reporank_scan: { path: '/api/reporank/scan', method: 'POST' },
        reporank_milestones: { path: '/api/reporank/milestones', method: 'POST' },
        reporank_gates: { path: '/api/reporank/gates/:id/evaluate', method: 'POST' },
        reporank_drift: { path: '/api/reporank/drift/:projectId', method: 'POST' },
        vibeserve_tools: { path: '/api/vibeserve/tools/:toolName', method: 'POST' },
        claw_protect_audit: { path: '/api/claw-protect/audit', method: 'POST' },
      },
      requires_env: ['MUTLY_URL'],
    },
    capabilities: ['code-indexing', 'semantic-search', 'symbol-extraction', 'sandbox-testing', 'progress-tracking'],
    source_type: 'github',
    source_url: 'https://github.com/tap919/Mutly-Daemon-Agent',
    download_path: 'agents/Mutly-Daemon-Agent',
    is_integrated: true,
    risk_level_default: 'low',
  },
  {
    name: 'AgentBrowser',
    slug: 'agent-browser',
    kind: 'tool',
    description: 'Multi-service autonomous agent orchestrator with Playwright browser automation — navigate, click, fill, extract page content, and run the Overlay365 QA suite. Gateway to Big Homie, Claw-Protect, Mutly, VibeServe, and RepoRank. Runs on localhost:3700 (canonical port — see ports.ts).',
    version: '1.0.0',
    tags: ['browser', 'automation', 'orchestrator', 'qa', 'playwright'],
    category: 'automation',
    sector: 'community',
    invocation_method: 'http_api',
    invocation_config: {
      // URL set at runtime via env — do not hardcode localhost
      url: 'http://localhost:3700', // AGENTBROWSER_URL
      method: 'POST',
      timeout_ms: 120000,
      endpoints: {
        browser_task: { path: '/api/browser-task', method: 'POST' },
        browser_control: { path: '/api/browser-control', method: 'POST' },
        site_tests: { path: '/api/testing', method: 'GET' },
      },
      requires_env: ['AGENTBROWSER_URL'],
    },
    capabilities: ['browser-automation', 'web-scraping', 'qa-testing', 'orchestration'],
    source_type: 'github',
    source_url: 'https://github.com/ncsound919/AgentBrowser',
    download_path: 'agents/AgentBrowser-main',
    is_integrated: true,
    risk_level_default: 'low',
  },
  {
    name: 'RepoRank',
    slug: 'reporank',
    kind: 'tool',
    description: 'Repository depth scoring and remediation — submits GitHub repos for deep analysis (code quality, security, architecture) and tracks progress via milestones, quality gates, and drift. Runs on localhost:3200 (canonical port — see ports.ts).',
    version: '1.0.0',
    tags: ['review', 'scoring', 'remediation', 'progress', 'milestones', 'gates'],
    category: 'engineering',
    sector: 'community',
    invocation_method: 'http_api',
    invocation_config: {
      // URL set at runtime via env — do not hardcode localhost
      url: 'http://localhost:3200', // REPORANK_URL
      method: 'POST',
      timeout_ms: 120000,
      headers: {},
      endpoints: {
        health: { path: '/api/health', method: 'GET' },
        scan: { path: '/api/v1/scans', method: 'POST' },
        scan_status: { path: '/api/v1/scans/:scanId', method: 'GET' },
        milestones: { path: '/api/v1/milestones', method: 'POST' },
        milestones_project: { path: '/api/v1/milestones/project/:projectId', method: 'GET' },
        gates_evaluate: { path: '/api/v1/gates/:id/evaluate', method: 'POST' },
        drift: { path: '/api/v1/drift/:projectId', method: 'POST' },
      },
      requires_env: ['REPORANK_URL', 'REPORANK_API_KEY'],
    },
    capabilities: ['repo-scoring', 'remediation', 'progress-tracking', 'milestones', 'quality-gates'],
    source_type: 'github',
    source_url: 'https://github.com/ncsound919/reporank',
    download_path: 'agents/reporank',
    is_integrated: true,
    risk_level_default: 'low',
  },
  {
    name: 'Grader',
    slug: 'grader',
    kind: 'tool',
    description: 'Data-backed code and repo grading — synchronous grade of a GitHub repo. Runs on localhost:3201 (canonical port — see ports.ts).',
    version: '1.0.0',
    tags: ['review', 'grading', 'scoring'],
    category: 'engineering',
    sector: 'community',
    invocation_method: 'http_api',
    invocation_config: {
      // URL set at runtime via env — do not hardcode localhost
      url: 'http://localhost:3201', // GRADER_URL
      method: 'POST',
      timeout_ms: 120000,
      endpoints: {
        health: { path: '/api/health', method: 'GET' },
        grade: { path: '/api/grade', method: 'POST' },
      },
      requires_env: ['GRADER_URL', 'GRADER_API_KEY'],
    },
    capabilities: ['repo-grading', 'scoring'],
    source_type: 'github',
    source_url: 'https://github.com/tap919/Grader',
    download_path: 'agents/Grader-main',
    is_integrated: true,
    risk_level_default: 'low',
  },
  {
    name: 'Graphify',
    slug: 'graphify',
    kind: 'tool',
    description: 'Codebase knowledge graph — deterministic tree-sitter AST mapping of the ecosystem into a queryable graph (graphify-out/graph.json). Served over MCP stdio on localhost:3203. Tools: query_graph, shortest_path, get_node, get_neighbors. Index with scripts/graphify-index.ps1.',
    version: '1.0.0',
    tags: ['knowledge-graph', 'codebase', 'mcp', 'ast', 'intelligence'],
    category: 'engineering',
    sector: 'community',
    invocation_method: 'mcp_stdio',
    invocation_config: {
      // Serves graphify-out/graph.json over the standard MCP handshake.
      // tool_name is omitted — the invocation action selects the graph tool.
      command: 'python',
      args: ['-m', 'graphify.serve', 'graphify-out/graph.json'],
      cwd: '.',
      timeout_ms: 60000,
      requires_env: ['GRAPHIFY_URL'],
    },
    capabilities: ['knowledge-graph', 'codebase-query', 'path-tracing', 'explain'],
    source_type: 'github',
    source_url: 'https://github.com/Graphify-Labs/graphify',
    download_path: 'graphify-out',
    is_integrated: true,
    risk_level_default: 'low',
  },
  {
    name: 'Deterministic Brain',
    slug: 'deterministic-brain',
    kind: 'tool',
    description: 'Metacognitive observer — runs Recognition → Labeling → Intervention over the Graphify knowledge graph and the ecosystem, emitting structured proposals (never auto-applied). FastAPI on localhost:3210. Sweep: POST /brain/sweep · Status: GET /brain/status.',
    version: '2.5.0',
    tags: ['metacognition', 'observer', 'self-awareness', 'proposals', 'sweep'],
    category: 'engineering',
    sector: 'community',
    invocation_method: 'http_api',
    invocation_config: {
      // URL set at runtime via env — do not hardcode localhost
      url: 'http://localhost:3210', // BRAIN_URL
      method: 'POST',
      timeout_ms: 120000,
      endpoints: {
        sweep: { path: '/brain/sweep', method: 'POST' },
        status: { path: '/brain/status', method: 'GET' },
        health: { path: '/health', method: 'GET' },
      },
      requires_env: ['BRAIN_URL'],
    },
    capabilities: ['metacognition', 'graph-observer', 'proposals', 'self-reflection', 'sweep'],
    source_type: 'github',
    source_url: 'https://github.com/ncsound919/deterministic-brain',
    download_path: 'agents/deterministic-brain',
    is_integrated: true,
    risk_level_default: 'low',
  },
  {
    name: 'Sub Team',
    slug: 'sub-team',
    kind: 'agent',
    description: 'Deterministic CPU RTL (Verilog) generation pipeline — 4 sequential agents: Specification, Microarchitecture, Implementation, and Verification. Supports RV32I/RV64I/MIPS32/ARM_M0 ISAs with single-cycle through out-of-order pipelines.',
    version: '1.0.0',
    tags: ['hardware', 'verilog', 'rtl', 'cpu-design', 'multi-agent'],
    category: 'dev-tools',
    sector: 'learn',
    invocation_method: 'cli_command',
    invocation_config: { command: 'python', args: ['main.py'], cwd: 'downloads/Sub-Team-main' },
    capabilities: ['cpu_rtl_generation', 'specification', 'microarchitecture', 'verification', 'cross_disciplinary_analysis'],
    source_type: 'github',
    download_path: 'downloads/Sub-Team-main',
    is_integrated: true,
    platform_page: '/tools/sub-team',
    is_free: false,
    price_cents: 2000,
  },
  {
    name: 'Social Media Dashboard',
    slug: 'social-media-dashboard',
    kind: 'service',
    description: 'B2B social media engagement and analytics dashboard.',
    version: '1.0.0',
    tags: ['social-media', 'b2b', 'analytics', 'engagement'],
    category: 'marketing',
    sector: 'ventures',
    invocation_method: 'api_call',
    capabilities: ['analytics', 'engagement', 'scheduling', 'reporting'],
    source_type: 'github',
    download_path: 'downloads/Social-Media-Dashboard--main',
    is_integrated: true,
    platform_page: '/tools/social-media-dashboard',
    is_free: false,
    price_cents: 2000,
  },
  {
    name: 'OmniResearch Pro',
    slug: 'omni-research',
    kind: 'agent',
    description: 'Automated RAG research pipeline — synthesizes document repositories into structured intelligence reports using Gemini. Supports local Ollama and SearXNG.',
    version: '1.0.0',
    tags: ['research', 'rag', 'synthesis', 'gemini', 'intelligence-reports'],
    category: 'research',
    sector: 'learn',
    invocation_method: 'http_api',
    invocation_config: {
      // URL set at runtime; starts with `npm run dev` or production deploy
      // Requires: GEMINI_API_KEY env var
      // Optional: OLLAMA_BASE_URL, OLLAMA_MODEL, SEARXNG_BASE_URL
      requires_env: ['GEMINI_API_KEY'],
      start_command: 'npm run dev',
      cwd: 'downloads/OmniResearch-Pro-main',
    },
    capabilities: ['rag-research', 'document-synthesis', 'intelligence-reports', 'web-search', 'search', 'analysis', 'generation'],
    source_type: 'github',
    download_path: 'downloads/OmniResearch-Pro-main',
    is_integrated: true,
    platform_page: '/tools/omni-research',
  },
  {
    name: 'Super Tool',
    slug: 'super-tool',
    kind: 'tool',
    description: 'Unified trading and marketing pipeline — combines financial analysis with marketing automation.',
    version: '1.0.0',
    tags: ['trading', 'marketing', 'pipeline', 'unified'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'cli_command',
    capabilities: ['trading', 'marketing', 'automation', 'analysis'],
    download_path: 'downloads/Uplift Agent',
  },
  {
    name: 'Browser Use',
    slug: 'browser-use',
    kind: 'tool',
    description: 'AI-powered browser automation — web scraping, form filling, and automated browsing workflows.',
    version: '1.0.0',
    tags: ['browser', 'automation', 'scraping'],
    category: 'automation',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'browser_use', function: 'run' },
    capabilities: ['automation', 'scraping', 'browser-control'],
  },
  {
    name: 'Everything Claude Code',
    slug: 'everything-claude-code',
    kind: 'tool',
    description: '28 agents, 116 skills, and comprehensive Claude Code ecosystem management.',
    version: '1.0.0',
    tags: ['claude', 'agents', 'skills', 'ecosystem'],
    category: 'dev-tools',
    sector: 'learn',
    invocation_method: 'cli_command',
    capabilities: ['orchestration', 'generation', 'analysis', 'automation'],
    download_path: 'downloads/Uplift Agent/everything-claude-code-main',
  },
  {
    name: 'Phaselock',
    slug: 'phaselock',
    kind: 'tool',
    description: '80 enforceable development rules — code quality, security, and best practices enforcement.',
    version: '1.0.0',
    tags: ['rules', 'enforcement', 'quality', 'security'],
    category: 'dev-tools',
    sector: 'learn',
    invocation_method: 'internal',
    capabilities: ['enforcement', 'validation', 'code-quality'],
    download_path: 'downloads/Uplift Agent/Phaselock-main',
  },
  {
    name: 'MoneyPrinterTurbo',
    slug: 'money-printer-turbo',
    kind: 'tool',
    description: 'Automated video generation tool — create monetizable video content at scale.',
    version: '1.0.0',
    tags: ['video', 'generation', 'monetization'],
    category: 'content',
    sector: 'ventures',
    invocation_method: 'cli_command',
    capabilities: ['generation', 'video-creation'],
  },
  {
    name: 'Swabble',
    slug: 'swabble',
    kind: 'tool',
    description: 'Wake-word daemon — always-listening voice activation for agent commands.',
    version: '1.0.0',
    tags: ['voice', 'wake-word', 'daemon'],
    category: 'voice',
    sector: 'community',
    invocation_method: 'cli_command',
    capabilities: ['voice-activation', 'listening'],
    download_path: 'downloads/Uplift Agent/Swabble',
  },
  {
    name: 'Ghostfolio',
    slug: 'ghostfolio',
    kind: 'tool',
    description: 'Open-source wealth management and portfolio tracking.',
    version: '1.0.0',
    tags: ['wealth', 'portfolio', 'tracking', 'open-source'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'api_call',
    capabilities: ['portfolio-tracking', 'analytics', 'reporting'],
  },
  {
    name: 'Block 2.0',
    slug: 'block-2',
    kind: 'tool',
    description: 'VS Code gamification extension — streaks, XP, and productivity tracking for developers.',
    version: '2.0.0',
    tags: ['vscode', 'gamification', 'productivity'],
    category: 'dev-tools',
    sector: 'learn',
    invocation_method: 'manual',
    capabilities: ['gamification', 'tracking'],
  },
];

// ============================================================================
// SKILLS (from downloads/Uplift Agent/skills/)
// ============================================================================

const skills: DraymondEntityInsert[] = [
  {
    name: 'Sports Betting Skill',
    slug: 'skill-sports-betting',
    kind: 'skill',
    description: 'Sports betting analysis, odds comparison, and bankroll management.',
    tags: ['sports', 'betting', 'odds'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.sports-betting' },
    capabilities: ['betting', 'analysis', 'prediction'],
    download_path: 'downloads/Uplift Agent/skills/sports-betting',
  },
  {
    name: 'Trading Skill',
    slug: 'skill-trading',
    kind: 'skill',
    description: 'Stock and crypto trading signals, technical analysis, and portfolio management.',
    tags: ['trading', 'stocks', 'crypto', 'technical-analysis'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.trading' },
    capabilities: ['trading', 'analysis', 'signals'],
    download_path: 'downloads/Uplift Agent/skills/trading',
  },
  {
    name: 'Skill Creator',
    slug: 'skill-creator',
    kind: 'skill',
    description: 'Meta-skill for creating new skills — scaffolding, templates, and validation.',
    tags: ['meta', 'creator', 'scaffolding'],
    category: 'dev-tools',
    sector: 'learn',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.skill-creator' },
    capabilities: ['generation', 'scaffolding'],
    download_path: 'downloads/Uplift Agent/skills/skill-creator',
  },
  {
    name: 'Marketing Tools Skill',
    slug: 'skill-marketing-tools',
    kind: 'skill',
    description: 'Marketing automation — email campaigns, social posting, content generation.',
    tags: ['marketing', 'automation', 'content'],
    category: 'marketing',
    sector: 'ventures',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.marketing-tools' },
    capabilities: ['marketing', 'generation', 'automation'],
    download_path: 'downloads/Uplift Agent/skills/marketing-tools',
  },
  {
    name: 'LLM Trading Lab',
    slug: 'skill-llm-trading-lab',
    kind: 'skill',
    description: 'LLM-powered trading strategy backtesting and signal generation.',
    tags: ['trading', 'llm', 'backtesting', 'signals'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.LLM-Trading-Lab' },
    capabilities: ['trading', 'analysis', 'backtesting'],
    download_path: 'downloads/Uplift Agent/skills/LLM-Trading-Lab',
  },
  {
    name: 'Trading Agents Skill',
    slug: 'skill-trading-agents',
    kind: 'skill',
    description: 'Multi-agent trading system — coordinated trading bots with different strategies.',
    tags: ['trading', 'multi-agent', 'bots'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.trading-agents' },
    capabilities: ['trading', 'automation', 'multi-agent'],
    download_path: 'downloads/Uplift Agent/skills/trading-agents',
  },
  {
    name: 'Engram Memory Skill',
    slug: 'skill-engram',
    kind: 'skill',
    description: 'Engram-based memory system — structured knowledge storage and retrieval.',
    tags: ['memory', 'knowledge', 'engram'],
    category: 'memory',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.engram' },
    capabilities: ['memory', 'retrieval', 'storage'],
    download_path: 'downloads/Uplift Agent/skills/engram',
  },
  {
    name: 'Mem0 Memory Skill',
    slug: 'skill-mem0',
    kind: 'skill',
    description: 'Mem0 integration — persistent memory with semantic search.',
    tags: ['memory', 'semantic-search', 'mem0'],
    category: 'memory',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.mem0' },
    capabilities: ['memory', 'search', 'storage'],
    download_path: 'downloads/Uplift Agent/skills/mem0',
  },
  {
    name: 'Block Hustlers Skill',
    slug: 'skill-block-hustlers',
    kind: 'skill',
    description: 'Community-driven hustler productivity and goal tracking.',
    tags: ['productivity', 'community', 'goals'],
    category: 'community',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.Block-Hustlers' },
    capabilities: ['tracking', 'gamification'],
    download_path: 'downloads/Uplift Agent/skills/Block-Hustlers',
  },
  {
    name: 'Sovereign Music Studio',
    slug: 'skill-sovereign-music',
    kind: 'skill',
    description: 'AI-powered music production — beat generation, mixing, and distribution.',
    tags: ['music', 'production', 'ai'],
    category: 'content',
    sector: 'ventures',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.sovereign-music-studio' },
    capabilities: ['generation', 'music-production'],
    download_path: 'downloads/Uplift Agent/skills/sovereign-music-studio',
  },
  {
    name: 'Digital Lab Skill',
    slug: 'skill-digital-lab',
    kind: 'skill',
    description: 'Digital experimentation and prototyping environment.',
    tags: ['lab', 'prototyping', 'experimentation'],
    category: 'dev-tools',
    sector: 'learn',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.digital-lab' },
    capabilities: ['prototyping', 'experimentation'],
    download_path: 'downloads/Uplift Agent/skills/digital-lab',
  },
  {
    name: 'OpenSandbox Skill',
    slug: 'skill-open-sandbox',
    kind: 'skill',
    description: 'Sandboxed code execution environment for safe experimentation.',
    tags: ['sandbox', 'execution', 'safety'],
    category: 'dev-tools',
    sector: 'learn',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.OpenSandbox' },
    capabilities: ['execution', 'sandboxing'],
    download_path: 'downloads/Uplift Agent/skills/OpenSandbox',
  },
  {
    name: 'Overlay Chain Skill',
    slug: 'skill-overlay-chain',
    kind: 'skill',
    description: 'Overlay chain integration — decentralized identity and reputation.',
    tags: ['blockchain', 'identity', 'reputation'],
    category: 'infrastructure',
    sector: 'justice',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.Overlay-Chain' },
    capabilities: ['identity', 'reputation', 'blockchain'],
    download_path: 'downloads/Uplift Agent/skills/Overlay-Chain',
  },
  {
    name: 'Voice Call Skill',
    slug: 'skill-voice-call',
    kind: 'skill',
    description: 'Voice calling and phone automation via AI.',
    tags: ['voice', 'calling', 'phone'],
    category: 'voice',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.voice-call' },
    capabilities: ['voice', 'calling', 'automation'],
    download_path: 'downloads/Uplift Agent/skills/voice-call',
  },
  {
    name: 'Weather Skill',
    slug: 'skill-weather',
    kind: 'skill',
    description: 'Weather data retrieval and forecasting.',
    tags: ['weather', 'data', 'forecast'],
    category: 'data',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.weather' },
    capabilities: ['search', 'data-retrieval'],
    download_path: 'downloads/Uplift Agent/skills/weather',
  },
  {
    name: 'XURL Skill',
    slug: 'skill-xurl',
    kind: 'skill',
    description: 'URL manipulation, link shortening, and web content extraction.',
    tags: ['url', 'web', 'extraction'],
    category: 'automation',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.xurl' },
    capabilities: ['scraping', 'extraction'],
    download_path: 'downloads/Uplift Agent/skills/xurl',
  },
  {
    name: 'Trello Skill',
    slug: 'skill-trello',
    kind: 'skill',
    description: 'Trello board management — create cards, manage lists, track progress.',
    tags: ['trello', 'project-management', 'boards'],
    category: 'productivity',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.trello' },
    capabilities: ['project-management', 'automation'],
    download_path: 'downloads/Uplift Agent/skills/trello',
  },
  {
    name: 'Video Frames Skill',
    slug: 'skill-video-frames',
    kind: 'skill',
    description: 'Video frame extraction and analysis.',
    tags: ['video', 'frames', 'analysis'],
    category: 'content',
    sector: 'ventures',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.video-frames' },
    capabilities: ['analysis', 'video-processing'],
    download_path: 'downloads/Uplift Agent/skills/video-frames',
  },
  {
    name: 'Spotify Player Skill',
    slug: 'skill-spotify-player',
    kind: 'skill',
    description: 'Spotify playback control and music recommendation.',
    tags: ['spotify', 'music', 'playback'],
    category: 'content',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.spotify-player' },
    capabilities: ['music', 'playback', 'recommendations'],
    download_path: 'downloads/Uplift Agent/skills/spotify-player',
  },
  {
    name: 'Summarize Skill',
    slug: 'skill-summarize',
    kind: 'skill',
    description: 'Text and document summarization using LLMs.',
    tags: ['summarization', 'nlp', 'text'],
    category: 'research',
    sector: 'learn',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.summarize' },
    capabilities: ['analysis', 'summarization'],
    download_path: 'downloads/Uplift Agent/skills/summarize',
  },
  {
    name: 'Bridge Skill',
    slug: 'skill-bridge',
    kind: 'skill',
    description: 'Cross-platform bridge for inter-agent communication.',
    tags: ['bridge', 'communication', 'cross-platform'],
    category: 'infrastructure',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.bridge' },
    capabilities: ['communication', 'bridging'],
    download_path: 'downloads/Uplift Agent/skills',
  },
  {
    name: 'Enhanced Skill',
    slug: 'skill-enhanced',
    kind: 'skill',
    description: 'Enhanced agent capabilities — improved reasoning and tool use.',
    tags: ['enhanced', 'reasoning', 'advanced'],
    category: 'core',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.enhanced' },
    capabilities: ['reasoning', 'analysis'],
    download_path: 'downloads/Uplift Agent/skills',
  },
  {
    name: 'Remote Control Skill',
    slug: 'skill-remote-control',
    kind: 'skill',
    description: 'Remote device control and IoT integration.',
    tags: ['remote', 'control', 'iot'],
    category: 'automation',
    sector: 'community',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.remote_control' },
    capabilities: ['automation', 'device-control'],
    download_path: 'downloads/Uplift Agent/skills',
  },
  {
    name: 'Budget Integration Skill',
    slug: 'skill-budget-integration',
    kind: 'skill',
    description: 'Personal budget tracking and financial planning integration.',
    tags: ['budget', 'finance', 'planning'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'python_module',
    invocation_config: { module: 'skills.budget_integration' },
    capabilities: ['budgeting', 'tracking', 'planning'],
    download_path: 'downloads/Uplift Agent/skills',
  },
];

// ============================================================================
// EXTENSIONS (key ones from downloads/Uplift Agent/extensions/)
// ============================================================================

const extensions: DraymondEntityInsert[] = [
  // --- AI Providers ---
  {
    name: 'OpenAI Provider',
    slug: 'ext-openai',
    kind: 'extension',
    description: 'OpenAI API integration — GPT-4, GPT-3.5, embeddings, DALL-E.',
    tags: ['ai-provider', 'openai', 'gpt'],
    category: 'ai-provider',
    invocation_method: 'python_module',
    capabilities: ['chat', 'generation', 'embedding'],
    download_path: 'downloads/Uplift Agent/extensions/openai',
  },
  {
    name: 'DeepSeek Provider',
    slug: 'ext-deepseek',
    kind: 'extension',
    description: 'DeepSeek AI model provider integration.',
    tags: ['ai-provider', 'deepseek'],
    category: 'ai-provider',
    invocation_method: 'python_module',
    capabilities: ['chat', 'generation'],
    download_path: 'downloads/Uplift Agent/extensions/deepseek',
  },
  {
    name: 'Ollama Provider',
    slug: 'ext-ollama',
    kind: 'extension',
    description: 'Ollama local model provider — run LLMs locally.',
    tags: ['ai-provider', 'ollama', 'local'],
    category: 'ai-provider',
    invocation_method: 'python_module',
    capabilities: ['chat', 'generation'],
    download_path: 'downloads/Uplift Agent/extensions/ollama',
  },
  {
    name: 'HuggingFace Provider',
    slug: 'ext-huggingface',
    kind: 'extension',
    description: 'HuggingFace model hub integration.',
    tags: ['ai-provider', 'huggingface'],
    category: 'ai-provider',
    invocation_method: 'python_module',
    capabilities: ['chat', 'generation', 'embedding'],
    download_path: 'downloads/Uplift Agent/extensions/huggingface',
  },
  // --- Memory Extensions ---
  {
    name: 'Engram Memory Extension',
    slug: 'ext-engram',
    kind: 'extension',
    description: 'Engram-based persistent memory with structured knowledge graphs.',
    tags: ['memory', 'engram', 'knowledge-graph'],
    category: 'memory',
    invocation_method: 'python_module',
    capabilities: ['memory', 'storage', 'retrieval'],
    download_path: 'downloads/Uplift Agent/extensions/engram',
  },
  {
    name: 'Mem0 Memory Extension',
    slug: 'ext-mem0',
    kind: 'extension',
    description: 'Mem0 memory extension — persistent memory with semantic search.',
    tags: ['memory', 'mem0', 'semantic'],
    category: 'memory',
    invocation_method: 'python_module',
    capabilities: ['memory', 'search', 'storage'],
    download_path: 'downloads/Uplift Agent/extensions/mem0',
  },
  {
    name: 'Memory Core Extension',
    slug: 'ext-memory-core',
    kind: 'extension',
    description: 'Core memory module — base memory infrastructure for all agents.',
    tags: ['memory', 'core', 'infrastructure'],
    category: 'memory',
    invocation_method: 'python_module',
    capabilities: ['memory', 'storage'],
    download_path: 'downloads/Uplift Agent/extensions/memory-core',
  },
  {
    name: 'LanceDB Memory Extension',
    slug: 'ext-memory-lancedb',
    kind: 'extension',
    description: 'LanceDB vector memory — high-performance vector storage for embeddings.',
    tags: ['memory', 'lancedb', 'vector', 'embeddings'],
    category: 'memory',
    invocation_method: 'python_module',
    capabilities: ['memory', 'embedding', 'vector-search'],
    download_path: 'downloads/Uplift Agent/extensions/memory-lancedb',
  },
  // --- Voice/Speech ---
  {
    name: 'Voice Extension',
    slug: 'ext-voice',
    kind: 'extension',
    description: 'Voice input/output — speech recognition and TTS.',
    tags: ['voice', 'speech', 'tts', 'stt'],
    category: 'voice',
    invocation_method: 'python_module',
    capabilities: ['voice', 'speech-recognition', 'text-to-speech'],
    download_path: 'downloads/Uplift Agent/extensions',
  },
  // --- Finance ---
  {
    name: 'Finance Extension',
    slug: 'ext-finance',
    kind: 'extension',
    description: 'Financial data feeds, market analysis, and trading hooks.',
    tags: ['finance', 'market-data', 'trading'],
    category: 'finance',
    invocation_method: 'python_module',
    capabilities: ['trading', 'data-retrieval', 'analysis'],
    download_path: 'downloads/Uplift Agent/extensions',
  },
  // --- Infrastructure ---
  {
    name: 'Browser Extension',
    slug: 'ext-browser',
    kind: 'extension',
    description: 'Browser automation extension — headless browsing and web interaction.',
    tags: ['browser', 'automation', 'headless'],
    category: 'automation',
    invocation_method: 'python_module',
    capabilities: ['browser-control', 'scraping', 'automation'],
    download_path: 'downloads/Uplift Agent/extensions/browser',
  },
  {
    name: 'Social Agent Extension',
    slug: 'ext-social-agent',
    kind: 'extension',
    description: 'Social media automation — posting, engagement, and analytics across platforms.',
    tags: ['social-media', 'automation', 'engagement'],
    category: 'marketing',
    invocation_method: 'python_module',
    capabilities: ['social-media', 'automation', 'engagement'],
    download_path: 'downloads/Uplift Agent/extensions/social-agent',
  },
  {
    name: 'Marketing Extension',
    slug: 'ext-marketing',
    kind: 'extension',
    description: 'Marketing automation hooks — email, content calendar, campaign management.',
    tags: ['marketing', 'automation', 'campaigns'],
    category: 'marketing',
    invocation_method: 'python_module',
    capabilities: ['marketing', 'automation', 'generation'],
    download_path: 'downloads/Uplift Agent/extensions/marketing',
  },
  {
    name: 'Overlay Chain Extension',
    slug: 'ext-overlay-chain',
    kind: 'extension',
    description: 'Overlay Chain blockchain integration extension.',
    tags: ['blockchain', 'overlay-chain', 'decentralized'],
    category: 'infrastructure',
    invocation_method: 'python_module',
    capabilities: ['blockchain', 'identity'],
    download_path: 'downloads/Uplift Agent/extensions/overlay-chain',
  },
  {
    name: 'Paperclip Extension',
    slug: 'ext-paperclip',
    kind: 'extension',
    description: 'Paperclip org-chart agent framework integration.',
    tags: ['paperclip', 'multi-agent', 'org-chart'],
    category: 'infrastructure',
    invocation_method: 'python_module',
    capabilities: ['orchestration', 'multi-agent'],
    download_path: 'downloads/Uplift Agent/extensions/paperclip',
  },
  // --- Research Extensions ---
  {
    name: 'AutoResearch Extension',
    slug: 'ext-autoresearch',
    kind: 'extension',
    description: 'Autonomous ML research framework (Karpathy-style). Automates the full research loop: hypothesis → GPU training run → metrics → next experiment. Requires NVIDIA GPU + CUDA 12.8 and uv package manager.',
    version: '0.1.0',
    tags: ['ml', 'research', 'pytorch', 'gpu', 'training', 'karpathy', 'hyperparameter-tuning', 'experiments'],
    category: 'research',
    sector: 'learn',
    invocation_method: 'subprocess',
    invocation_config: {
      // Loaded by OpenClaw/Hermes at startup as an agent plugin
      // Python backend expected at: <repo-root>/Claw Life/autoresearch-main/
      plugin_entry: 'downloads/Uplift Agent/extensions/autoresearch/src/autoresearch-engine.ts',
      python_backend_cwd: 'Claw Life/autoresearch-main',
      train_command: ['uv', 'run', 'train.py'],
      prepare_command: ['uv', 'run', 'prepare.py'],
      timeout_ms: 600000, // 10 minutes
      requires_env: ['NVIDIA_GPU', 'CUDA_12_8'],
    },
    capabilities: [
      'ml-research',
      'hyperparameter-tuning',
      'gpu-training',
      'experiment-tracking',
      'analysis',
      'generation',
    ],
    download_path: 'downloads/Uplift Agent/extensions/autoresearch',
    timeout_seconds: 600,
    risk_level_default: 'medium', // GPU training — significant compute resource usage
  },
  // --- Agent Orchestration ---
  {
    name: 'Draymond Supervisor',
    slug: 'ext-draymond-supervisor',
    kind: 'extension',
    description: 'OpenClaw plugin that connects to the Draymond orchestration backend. Handles sub-agent lifecycle (spawn, health, auto-restart), budget allocation per agent, and task dispatch. Requires Draymond API server running at localhost:8000.',
    version: '0.1.0',
    tags: ['orchestration', 'supervision', 'draymond', 'multi-agent', 'health-monitoring'],
    category: 'infrastructure',
    sector: 'community',
    invocation_method: 'http_api',
    invocation_config: {
      // HTTP calls to Draymond Supervisor backend
      // URL set at runtime via env; default http://localhost:8000
      requires_env: ['DRAYMOND_API_KEY'],
      default_url: 'http://localhost:8000',
      plugin_entry: 'downloads/Uplift Agent/extensions/draymond-supervisor/index.ts',
      max_agents: 10,
      budget_per_agent_usd: 1000,
      health_check_interval_ms: 30000,
      auto_restart: true,
    },
    capabilities: ['orchestration', 'monitoring', 'multi-agent', 'health-checking', 'budget-management'],
    download_path: 'downloads/Uplift Agent/extensions/draymond-supervisor',
    risk_level_default: 'medium', // Agent lifecycle control — restart and budget ops
  },
  // --- Finance / Wealth ---
  {
    name: 'The Bank',
    slug: 'ext-the-bank',
    kind: 'extension',
    description: 'AI-powered wealth management and financial planning. Combines Ghostfolio portfolio tracking with FinGPT market analysis and robo-advisory services. Supports automatic rebalancing with configurable thresholds and risk tolerance (conservative/moderate/aggressive).',
    version: '0.1.0',
    tags: ['wealth', 'finance', 'portfolio', 'ghostfolio', 'fingpt', 'robo-advisor', 'rebalancing'],
    category: 'finance',
    sector: 'wealth',
    invocation_method: 'http_api',
    invocation_config: {
      // HTTP to Ghostfolio (localhost:3333) and FinGPT (localhost:8000)
      // LLM analysis via OpenRouter
      requires_env: ['GHOSTFOLIO_API_KEY', 'OPENROUTER_API_KEY'],
      ghostfolio_url: 'http://localhost:3333',
      fingpt_url: 'http://localhost:8000',
      plugin_entry: 'downloads/Uplift Agent/extensions/the-bank/index.ts',
      default_risk_tolerance: 'moderate',
      advisory_fee_percent: 1.0,
      enable_rebalancing: false,
      rebalance_threshold_percent: 5,
    },
    capabilities: ['portfolio-tracking', 'wealth-analysis', 'robo-advisory', 'rebalancing', 'market-analysis', 'financial-planning'],
    download_path: 'downloads/Uplift Agent/extensions/the-bank',
    risk_level_default: 'medium', // Financial decisions — portfolio rebalancing
  },
  // --- Multi-Agent Orchestration ---
  {
    name: 'ClawTeam',
    slug: 'ext-claw-team',
    kind: 'extension',
    description: 'Agent swarm intelligence. A leader agent assigns tasks to worker agents running in isolated git worktrees and tmux sessions, monitors progress, and synthesizes results. Transport: file-based (default) or ZeroMQ.',
    version: '0.1.0',
    tags: ['swarm', 'multi-agent', 'orchestration', 'worktrees', 'tmux', 'parallel'],
    category: 'infrastructure',
    sector: 'community',
    invocation_method: 'subprocess',
    invocation_config: {
      // Python/Node subprocess via ClawTeam CLI
      // Backend expected at: Claw Life/ClawTeam-main/
      plugin_entry: 'downloads/Uplift Agent/extensions/claw-team/index.ts',
      claw_team_dir: 'Claw Life/ClawTeam-main',
      transport: 'file', // 'file' or 'zeromq'
      timeout_ms: 60000,
      tools: ['clawteam_spawn_team', 'clawteam_spawn_worker', 'clawteam_get_board'],
    },
    capabilities: ['swarm-orchestration', 'task-delegation', 'parallel-execution', 'result-synthesis', 'multi-agent'],
    download_path: 'downloads/Uplift Agent/extensions/claw-team',
    timeout_seconds: 60,
    risk_level_default: 'medium', // Spawns subprocesses and manages git worktrees
  },
  // --- LLM Infrastructure ---
  {
    name: 'ClawRouter',
    slug: 'ext-claw-router',
    kind: 'extension',
    description: 'Intelligent LLM router. Automatically routes requests to the cheapest or best-fit model with sub-1ms latency. Features LRU caching, cost tracking, and a BlockRun proxy on port 8402.',
    version: '0.1.0',
    tags: ['llm-router', 'cost-optimization', 'model-routing', 'caching', 'blockrun'],
    category: 'infrastructure',
    sector: 'community',
    invocation_method: 'http_api',
    invocation_config: {
      // HTTP proxy at localhost:8402 (BlockRun)
      // URL set at runtime — no hardcoded address
      default_proxy_url: 'http://localhost:8402',
      plugin_entry: 'downloads/Uplift Agent/extensions/claw-router/index.ts',
      timeout_ms: 30000,
      tools: ['router_check_health', 'router_get_stats', 'router_get_cache'],
    },
    capabilities: ['model-routing', 'cost-optimization', 'caching', 'cost-tracking', 'load-balancing'],
    download_path: 'downloads/Uplift Agent/extensions/claw-router',
    risk_level_default: 'low',
  },
  // --- Education ---
  {
    name: 'The Lab',
    slug: 'ext-the-lab',
    kind: 'extension',
    description: 'AI-powered education and learning assistant using the OSS.U open-source CS curriculum. Provides code tutoring, personalized learning paths, and session-based billing. Uses OpenRouter for LLM calls.',
    version: '0.1.0',
    tags: ['education', 'tutoring', 'ossu', 'curriculum', 'learning', 'coding'],
    category: 'research',
    sector: 'learn',
    invocation_method: 'http_api',
    invocation_config: {
      // LLM calls via OpenRouter; data stored locally
      requires_env: ['OPENROUTER_API_KEY'],
      default_model: 'claude-3-5-sonnet-20241022',
      data_dir: '~/.openclaw/the-lab/data',
      tutoring_fee_usd: 15.0,
      plugin_entry: 'downloads/Uplift Agent/extensions/the-lab/index.ts',
      tools: ['lab_list_courses'],
    },
    capabilities: ['tutoring', 'curriculum-guidance', 'code-review', 'learning-paths', 'education', 'analysis'],
    download_path: 'downloads/Uplift Agent/extensions/the-lab',
    risk_level_default: 'low',
  },
  // --- Security ---
  {
    name: 'Cyber Security',
    slug: 'ext-cyber-security',
    kind: 'extension',
    description: 'AI-powered cybersecurity operations via the CAI framework. Covers red teaming, penetration testing, digital forensics and incident response (DFIR), and vulnerability analysis. Spawns a Python CAI subprocess per scan.',
    version: '0.1.0',
    tags: ['security', 'red-team', 'pen-testing', 'dfir', 'vulnerability', 'cai', 'forensics'],
    category: 'infrastructure',
    sector: 'justice',
    invocation_method: 'subprocess',
    invocation_config: {
      // Python subprocess via CAI framework
      // Agent types: red_teamer, blue_teamer, bug_bounter, web_pentester,
      //              dfir, reporter, network_traffic_analyzer,
      //              android_sast_agent, reverse_engineering_agent
      plugin_entry: 'downloads/Uplift Agent/extensions/cyber-security/index.ts',
      timeout_ms: 300000, // 5 minutes — security scans can be slow
      tools: ['security_scan'],
    },
    capabilities: ['red-teaming', 'pen-testing', 'dfir', 'vulnerability-analysis', 'security-scanning', 'forensics'],
    download_path: 'downloads/Uplift Agent/extensions/cyber-security',
    timeout_seconds: 300,
    risk_level_default: 'high', // Active security scanning — can trigger alerts on target systems
  },
];

// ============================================================================
// MCP SERVERS
// ============================================================================

const mcpServers: DraymondEntityInsert[] = [
  {
    name: 'UFC-MCP',
    slug: 'ufc-mcp',
    kind: 'mcp_server',
    description: 'Universal File Converter MCP server — convert between file formats via the Model Context Protocol. 18+ tools: convert_audio / video / image / document / spreadsheet / archive / font / 3d / email / music / biotech / fintech / logistics / dev_format / statistics / chemistry / astronomy / geoscience, plus batch_convert, get_supported_formats, get_conversion_history.',
    version: '1.0.0',
    tags: ['mcp', 'file-conversion', 'utility'],
    category: 'utility',
    sector: 'community',
    invocation_method: 'mcp_stdio',
    invocation_config: {
      // Spawns the MCP server via `node dist/index.js` and drives its tools
      // through the standard MCP handshake. tool_name is omitted so the
      // invocation action selects the convert_* tool (e.g. convert_document).
      command: 'node',
      args: ['dist/index.js'],
      cwd: 'agents/UFC-MCP-main',
      timeout_ms: 120000,
    },
    capabilities: ['file-conversion', 'utility', 'document-to-markdown', 'spreadsheet', 'audio', 'video', 'image'],
    download_path: 'agents/UFC-MCP-main',
    is_integrated: true,
    risk_level_default: 'low',
  },
  {
    name: 'CIS Assistant',
    slug: 'mcp-cis-assistant',
    kind: 'mcp_server',
    description: 'UK Construction Industry Scheme (CIS) contract management and compliance tool. Generates compliant contracts, validates them, calculates CIS deduction rates (20%/30%/0%), onboards businesses, and provides compliance checklists. Spawns a Python MCP server subprocess per call.',
    version: '0.1.0',
    tags: ['cis', 'construction', 'uk-tax', 'hmrc', 'contracts', 'compliance', 'subcontractors'],
    category: 'finance',
    sector: 'ventures',
    invocation_method: 'mcp_stdio',
    invocation_config: {
      // Loaded by OpenClaw/Hermes at startup as an agent plugin
      // Python backend expected at: <repo-root>/Claw Life/CIS-Assistant--main/
      plugin_entry: 'downloads/Uplift Agent/extensions/cis-assistant/src/cis-assistant-engine.ts',
      python_backend_cwd: 'Claw Life/CIS-Assistant--main',
      server_command: ['python', '-m', 'cis_assistant_mcp.server'],
      protocol: 'json-rpc-2.0',
      protocol_version: '2024-11-05',
      spawn_mode: 'one_shot', // Fresh subprocess per call: init → tool call → SIGTERM
      timeout_ms: 120000, // 2 minutes
      // Daily cron: cis-daily-contract-generation.json — 9 AM, 5-min timeout, 2 retries, Slack output
    },
    capabilities: [
      'cis-contracts',
      'compliance',
      'tax-deductions',
      'subcontractor-onboarding',
      'generation',
      'validation',
    ],
    download_path: 'downloads/Uplift Agent/extensions/cis-assistant',
    timeout_seconds: 120,
    risk_level_default: 'medium', // Contract generation — legal/financial implications
  },
];

// ============================================================================
// SERVICES (External integrations)
// ============================================================================

const services: DraymondEntityInsert[] = [
  {
    name: 'Local SQLite',
    slug: 'service-local-sqlite',
    kind: 'service',
    description: 'Local SQLite database (better-sqlite3) — all Draymond state, private and zero-cost.',
    tags: ['database', 'local', 'storage'],
    category: 'infrastructure',
    invocation_method: 'api_call',
    invocation_config: { url: 'DRAYMOND_DB_PATH', auth_type: 'local' },
    capabilities: ['database', 'storage'],
    is_integrated: true,
  },
  {
    name: 'Vercel',
    slug: 'service-vercel',
    kind: 'service',
    description: 'Vercel deployment platform — hosting, edge functions, and CI/CD.',
    tags: ['hosting', 'deployment', 'edge'],
    category: 'infrastructure',
    invocation_method: 'api_call',
    capabilities: ['deployment', 'hosting'],
    is_integrated: true,
  },
  {
    name: 'Stripe',
    slug: 'service-stripe',
    kind: 'service',
    description: 'Stripe payment processing — subscriptions, one-time payments, invoicing.',
    tags: ['payments', 'subscriptions', 'billing'],
    category: 'finance',
    invocation_method: 'api_call',
    capabilities: ['payments', 'subscriptions', 'invoicing'],
    is_integrated: true,
  },
  {
    name: 'OpenAI API',
    slug: 'service-openai-api',
    kind: 'service',
    description: 'OpenAI API service — GPT-4, GPT-3.5, embeddings, DALL-E, Whisper.',
    tags: ['ai', 'openai', 'api'],
    category: 'ai-provider',
    invocation_method: 'api_call',
    invocation_config: { url: 'https://api.openai.com/v1', auth_type: 'bearer' },
    capabilities: ['chat', 'generation', 'embedding', 'speech'],
    is_integrated: true,
  },
  {
    name: 'Gumroad Store',
    slug: 'service-gumroad',
    kind: 'service',
    description: 'Gumroad/Overlay365 storefront — digital product sales for TapClaw, agents, and bundles.',
    tags: ['store', 'digital-products', 'sales'],
    category: 'commerce',
    invocation_method: 'api_call',
    capabilities: ['commerce', 'distribution'],
    source_url: 'https://overlay365.gumroad.com',
  },
  {
    name: 'HempForge',
    slug: 'hempforge',
    kind: 'service',
    description: 'Agentic compliance, COA verification, and scientific literature intelligence platform for regulated hemp operations. COA intake (Gemini/Ollama/regex fallback), ALCOA++ hash-chained compliance ledger, 5-stage GxP workflow lifecycle, and a literature trend engine (Mann-Kendall, Kleinberg bursts, cross-source validation, regulatory risk scoring). Every AI output carries a provenance classification (live-ai / deterministic / heuristic / simulated / demo-only).',
    version: '1.0.0',
    tags: ['hemp', 'compliance', 'coa', 'literature', 'audit', 'gxp', 'regulatory', 'provenance'],
    category: 'compliance',
    sector: 'ventures',
    invocation_method: 'http_api',
    invocation_config: {
      url: 'http://localhost:3000', // HEMPFORGE_URL at runtime — do not hardcode
      method: 'POST',
      health_url: 'http://localhost:3000/api/health',
      endpoints: {
        literature_search: '/api/literature/search',
        literature_ingest_defaults: '/api/literature/ingest-defaults',
        literature_trends: '/api/literature/trends-insights',
        literature_trend_snapshot: '/api/literature/trend-snapshot',
        literature_autonomous: '/api/literature/run-autonomous-pipeline',
        literature_production: '/api/literature/production/run',
        coa_list: '/api/coas',
        audit_logs: '/api/audit/logs',
        audit_verify_chain: '/api/audit/verify-chain',
        compliance_calculate: '/api/compliance/calculate',
        reports_generate: '/api/reports/generate',
        workflow_transition: '/api/workflows/:id/transition',
      },
      requires_env: ['HEMPFORGE_URL', 'GEMINI_API_KEY'],
    },
    capabilities: [
      'coa_intake',
      'compliance_ledger',
      'audit_trail',
      'literature_intelligence',
      'trend_detection',
      'regulatory_risk',
      'workflow_management',
      'reporting',
      'analysis',
    ],
    download_path: 'potential/HempForge-main',
    is_integrated: true,
    risk_level_default: 'medium',
  },
  {
    name: 'Recursive IP Builder',
    slug: 'recursive-ip',
    kind: 'service',
    description: 'Intellectual property platform — create, grade, and tokenize IP on-chain. Supports patent, trademark, copyright, trade secret, industrial design, and trade dress. Five-dimension grading (novelty, non-obviousness, usefulness, market potential, implementation complexity), NFT minting, portfolio analytics, keyword search, IP comparison, version history, and IP lineage/relationships.',
    version: '1.0.0',
    tags: ['ip', 'patent', 'trademark', 'copyright', 'blockchain', 'nft', 'grading'],
    category: 'finance',
    sector: 'justice',
    invocation_method: 'http_api',
    invocation_config: {
      url: 'http://localhost:8000', // RECURSIVE_IP_URL at runtime — do not hardcode
      method: 'POST',
      health_url: 'http://localhost:8000/api/v1/health',
      endpoints: {
        create: '/api/v1/ip',
        list: '/api/v1/ip',
        get: '/api/v1/ip/{id}',
        update: '/api/v1/ip/{id}',
        delete: '/api/v1/ip/{id}',
        grade: '/api/v1/grade',
        grade_by_id: '/api/v1/ip/{id}/grade',
        mint: '/api/v1/ip/{id}/mint',
        analytics: '/api/v1/ip/analytics',
        search: '/api/v1/ip/search',
        compare: '/api/v1/ip/compare',
        export: '/api/v1/ip/{id}/export',
        history: '/api/v1/ip/{id}/history',
        relationships: '/api/v1/ip/{id}/relationships',
      },
    },
    capabilities: [
      'ip_registry',
      'ip_grading',
      'nft_minting',
      'portfolio_analytics',
      'ip_search',
      'ip_comparison',
      'version_history',
      'ip_relationships',
      'blockchain',
    ],
    download_path: 'potential/Recursive-IP-Builder--main',
    is_integrated: true,
    is_free: false,
    price_cents: 2000,
    risk_level_default: 'low',
  },
];

// ============================================================================
// EXPORT ALL SEED DATA
// ============================================================================

export const SEED_ENTITIES: DraymondEntityInsert[] = [
  ...agents,
  ...tools,
  ...skills,
  ...extensions,
  ...mcpServers,
  ...services,
];

/**
 * Get seed data counts by kind.
 */
export function getSeedSummary(): Record<string, number> {
  return {
    agents: agents.length,
    tools: tools.length,
    skills: skills.length,
    extensions: extensions.length,
    mcp_servers: mcpServers.length,
    services: services.length,
    total: SEED_ENTITIES.length,
  };
}
