# Boots real Hermes api_server adapter on 8642 for the mission brain.
# The config (~/.hermes/config.yaml) is generated by scripts/hermes-config.mjs
# (run it once, or it will be regenerated below). Keys live in ~/.hermes/.env.
#
# Run in a dedicated terminal:  powershell -ExecutionPolicy Bypass -File <this>

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root '.env.local'
if (-not (Test-Path -LiteralPath $envFile)) { throw "missing $envFile" }

# Load Draymond's canonical env into the process so Hermes inherits it.
Get-Content -LiteralPath $envFile | ForEach-Object {
    if ($_ -match '^(?<k>[A-Z_][A-Z0-9_]*)=(?<v>.*)$') {
        Set-Item -Path "Env:\$($Matches.k)" -Value $Matches.v
    }
}

# Re-generate the Hermes config from .env.local (idempotent; backs up first).
& node "$root/scripts/hermes-config.mjs"
if ($LASTEXITCODE -ne 0) { throw "hermes-config failed" }

# The single OPENCODE_API_KEY serves both zen (free) and go (paid) tiers.
$env:OPENCODE_ZEN_API_KEY = $env:OPENCODE_API_KEY
$env:OPENCODE_GO_API_KEY = $env:OPENCODE_API_KEY

Write-Host "[hermes-brain] starting Hermes api_server on http://127.0.0.1:8642"
& hermes gateway
